### ISSUE TITLE
[Roadmap] v0.1.1 release plan

### ISSUE THREAD

**Issue by classicsong** [awslabs/dgl-ke#114]
## v0.1.1 Release
Although it is a minor release, but we will introduce several interesting features:

### Feature enhancement
 - [x] Offline inference support
 - [x] Support different delimiters for UDD

### Fix bugs
 - [x] Issue #85 
 - [x] Issue #99 
 - [x] Issue #97 

### Documentation enhancement
 - [x] Installation Guidelines
 - [x] Knowledge graphs and embeddings
 - [x] DGL-KE Toolkit Command Line Interface
 - [x] DGL-KE Input/output format
 - [x] Tips of Training and Evaluating Large Dataset
